---
- name: Install system packages
  action: apt name={{ item }}
  with_items:
    - python3-pip
    - python3-dev

- name: Install specified python
  pip: name={{ item }}
  with_items:
    - sleekxmpp==1.3.1